import xlsxwriter

outWorkbook2 = xlsxwriter.Workbook(f"test_data_1.xlsx")

outSheet2 = outWorkbook2.add_worksheet(name = '0')
outSheet2 = outWorkbook2.add_worksheet(name = '1')
outSheet2 = outWorkbook2.add_worksheet(name = '2')
outSheet2 = outWorkbook2.add_worksheet(name = '3')
outSheet2 = outWorkbook2.add_worksheet(name = '4')
outSheet2 = outWorkbook2.add_worksheet(name = '5')
outSheet2 = outWorkbook2.add_worksheet(name = '6')
outSheet2 = outWorkbook2.add_worksheet(name = '7')
outSheet2 = outWorkbook2.add_worksheet(name = '8')
outSheet2 = outWorkbook2.add_worksheet(name = '9')
outSheet2 = outWorkbook2.add_worksheet(name = '10')
outSheet2 = outWorkbook2.add_worksheet(name = '11')
outSheet2 = outWorkbook2.add_worksheet(name = '12')
outSheet2 = outWorkbook2.add_worksheet(name = '13')
outSheet2 = outWorkbook2.add_worksheet(name = '14')
outSheet2 = outWorkbook2.add_worksheet(name = '15')
outSheet2 = outWorkbook2.add_worksheet(name = '16')
outSheet2 = outWorkbook2.add_worksheet(name = '17')
outSheet2 = outWorkbook2.add_worksheet(name = '18')
outSheet2 = outWorkbook2.add_worksheet(name = '19')
outSheet2 = outWorkbook2.add_worksheet(name = '20')
outSheet2 = outWorkbook2.add_worksheet(name = '21')
outSheet2 = outWorkbook2.add_worksheet(name = '22')
outSheet2 = outWorkbook2.add_worksheet(name = '23')

outWorkbook2.close()